name: docs

on:
  push:
    branches:
      - main
jobs:
  docs:
    name: build rustdocs and put them on github pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Build Documentation
      run: cargo doc --workspace

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
