name: publish-crate

on:
  release:
    types: [published]

jobs:
  crate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: cargo publish
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.DIVVIUP_GITHUB_AUTOMATION_CRATES_IO_API_TOKEN }}
